import { Injectable } from '@angular/core';
import { Oferta } from './oferta';

@Injectable()
export class OfertaService {
  listaOfertas: Array<Oferta> = [
    new Oferta('../../../assets/telefonica1.png', 'Telefonica', 'MAQUETADOR WEB', '1 hora', 'Madrid, (España)', 'Grado Medio informática', '2 años', ['CSS3', 'HTML5', 'Photoshop', 'Git', 'Illustrator.'], 'En estos momentos necesitamos incorporar a nuestro EQUIPO un Maquetador Web Senior para el desarrollo de contenido e-learning con experiencia en Javascript, JQuery, peticiones Web (Rest) y conocimientos de otros Frameworks como Angular.', 3, 'Larga duración', '13.000€', 'Jornada completa', ['hola', 'hola']),
    new Oferta('../../../assets/telefonica1.png', 'Grupo Agio', 'Perfiles Java: Coordinador equipo y AP J2ee', '3 horas', 'Barcelona, Barcelona (España)', 'Cualquier persona que pueda demostrar sus conocimientos, valorándose estudios en informática o ingeniería.', 'Entre 2 y 3 años.', ['JQuery', 'HTML', 'CSS', 'Javascript.'], 'Seleccionamos programadores Java con experiencia en desarollo web y que se defienda tanto a nivel de backend como frontend para formar parte de nuestro equipo de desarrollo en un importante cliente final dedicado al marketing online y ubicado en Barcelona. Se tratan de proyectos nuevos, relacionados con las RRSS.', 3, 'Larga duración', '20.000€', 'Flexibilidad horaria', ['hola', 'hola']),
    new Oferta('../../../assets/telefonica1.png', 'ECADE ECONOMISTAS ASESORES DE EMPRESA, S.A', 'GRADUADO/ LICENCIADO EN LA RAMA ECONOMÍA', '10 horas', 'Pontevedra, (España)', 'Licenciados/ Graduados en Economía con experiencia en Fiscalidad.', 'Al menos 2 años', ['Gretl', 'Stata', 'E-views.'], 'Se solicita Titulados en la rama de Economía con experiencia en Fiscalidad con residencia en zonas próximas a ciudad de Pontevedra.', 1, 'Larga duración', '12.000€-15.000€ Bruto/año', 'Jornada completa', ['hola', 'hola']),
    new Oferta('../../../assets/telefonica1.png', 'ERM ARQUITECTOS SOCIEDAD LIMITADA', 'Arquitecto Urbanista', 'Hace 1 día', 'Tomares, Sevilla (España)', 'Ingeniero Superior - Arquitecto', 'Al menos 3 años', ['CSS3', 'HTML5', 'Photoshop', 'Git', 'Illustrator.'], 'Se precisa incorporar para el Departamento Técnico un ARQUITECTO URBANISTA para su sede en Sevilla. La persona seleccionada se encargara de desempeñar las siguientes funciones entre otras: - Tramitación y desarrollo de Gestión Urbanistica. -Planes parciales. -Estudios de detalles. -Modificaciones puntuales de elementos', 1, 'Larga duración', 'no disponible', 'Jornada completa', ['hola', 'hola']),
    new Oferta('../../../assets/telefonica1.png', 'Factum IT', 'Programador Junior SQL HTML', '1 día', 'Barcelona, Barcelona (España)', 'Cursando: Formación Profesional Grado Superior- Informática', 'No requerida', ['Perl', 'HTML', 'SQL', 'PHP'], 'Factum IT necesita incorporar par uno de sus proyectos en cliente un programador SQL HTML.', 1, '3 meses con posibilidad de incorporacion al actual equipo de desarrollo.', '600€- 900€ Bruto/mes (5 euros/ hora)', 'FLEXIBLE 4 h.', ['hola', 'hola']),
    new Oferta('../../../assets/telefonica1.png', 'TES', 'Perfil FULLSTACK. J2EE, Angular, Spring, HTML...', '2 días', 'A Coruña, A Coruña (España)', 'Ciclo Formativo Grado Superior- Informática', 'Perfil entre 2 y 6 meses de experiencia: Programador con experiencia o Analista Programador.', ['JAVA', 'HTML', 'JavaScript', 'CSS', 'J2EE', 'Hibernate', 'AngularJS'], 'Somos headhunters especialistas en la búsqueda y selección de perfiles Executive Tech. Acompañamos a profesionales y ejecutivos en los procesos de transición entre grandes empresas tecnológicas con profesionalidad y discreción. Sabemos de tecnología, tenemos probablemente la red de contactos IT mas amplia del mercado y estamos en contacto permanente con cerca de 400 empresas de tecnología y comunicaciones. Buscamos perfiles tecnológicos prófesionales que sepan adaptarse a los cambios, que trabajen con metodológias ágiles y que tengan una mente creativa e innovadora. Estamos seleccionando en LA CORUÑA, el perfil FULLSTACK: java, J2EE, Spring, Angular, CSS... ', 3, 'Larga duración', '13.000€', 'Jornada completa', ['hola', 'hola']),
    new Oferta('../../../assets/telefonica1.png', 'Telefonica', 'Maquetador web', '1 hora', 'Madrid', 'Grado Medio informática', '2 años', ['CSS3', 'HTML5', 'Photoshop', 'Git', 'Illustrator.'], 'En estos momentos necesitamos incorporar a nuestro EQUIPO un Maquetador Web Senior para el desarrollo de contenido e-learning con experiencia en Javascript, JQuery, peticiones Web (Rest) y conocimientos de otros Frameworks como Angular.', 3, 'Larga duración', '13.000€', 'Jornada completa', ['hola', 'hola']),
    new Oferta('../../../assets/telefonica1.png', 'Telefonica', 'Maquetador web', '1 hora', 'Madrid', 'Grado Medio informática', '2 años', ['CSS3', 'HTML5', 'Photoshop', 'Git', 'Illustrator.'], 'En estos momentos necesitamos incorporar a nuestro EQUIPO un Maquetador Web Senior para el desarrollo de contenido e-learning con experiencia en Javascript, JQuery, peticiones Web (Rest) y conocimientos de otros Frameworks como Angular.', 3, 'Larga duración', '13.000€', 'Jornada completa', ['hola', 'hola']),
    new Oferta('../../../assets/telefonica1.png', 'Telefonica', 'Maquetador web', '1 hora', 'Madrid', 'Grado Medio informática', '2 años', ['CSS3', 'HTML5', 'Photoshop', 'Git', 'Illustrator.'], 'En estos momentos necesitamos incorporar a nuestro EQUIPO un Maquetador Web Senior para el desarrollo de contenido e-learning con experiencia en Javascript, JQuery, peticiones Web (Rest) y conocimientos de otros Frameworks como Angular.', 3, 'Larga duración', '13.000€', 'Jornada completa', ['hola', 'hola']),
  ];
  constructor() { }

  devolverOfertas(): Array<Oferta> {
    return this.listaOfertas;
  }

  devolverOferta(id: any) {
    return this.listaOfertas[id];
  }

}
